server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.178.142.244:3306/db_housewifery?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: JX200219
    password: JX200219
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mapper/*.xml
